const colors = {
  light: {
    text: "#fafafa",
    tint: "#f43e5c",
    background: "#000000",
    foreground: "#fafafa",
    card: "#0a0a0a",
    cardForeground: "#fafafa",
    primary: "#f43e5c",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    accent: "#1f1f1f",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1f1f1f",
    input: "#1f1f1f",
  },
  dark: {
    text: "#fafafa",
    tint: "#f43e5c",
    background: "#000000",
    foreground: "#fafafa",
    card: "#0a0a0a",
    cardForeground: "#fafafa",
    primary: "#f43e5c",
    primaryForeground: "#ffffff",
    secondary: "#1a1a1a",
    secondaryForeground: "#fafafa",
    muted: "#262626",
    mutedForeground: "#a3a3a3",
    accent: "#1f1f1f",
    accentForeground: "#fafafa",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#1f1f1f",
    input: "#1f1f1f",
  },
  radius: 8,
};

export default colors;
